### ISSUE TITLE
Auto save scavenger hunt.

### ISSUE THREAD

**Issue by lilymzhou** [googleinterns/step183-2020#25]
Store the current destination that the user is on as an index. When the user logs back in, this scavenger hunt will be automatically displayed to the user.

One way to implement this would be to, when the user clicks the Exit button, add a pop-up message to the user telling them to save/bookmark the current URL (which contains a unique huntID), so that they could return to the same hunt at a later time.

**Comment by tjgoog** [comment]
"When the user logs back in, this scavenger hunt will be automatically displayed to the user." I don't think this part is done? I don't think login is set up yet.
